### ISSUE TITLE
Brackets in multiline literals broken

### ISSUE THREAD

**Issue by darvid** [uiri/toml#152]
I can't seem to find a ticket or anything in the spec that would explain this behavior. I'm using TOML as the format for a configuration file which will store a large number of regular expressions in multiline literals. One of these expressions contains a character class with a single quote, and causes the entire value to be parsed as an empty object.

I could reproduce this behavior by using a multiline literal in combination with newlines *either at the end of the multiline literal* or *at the end of the TOML configuration file*. This is the weird part: either the multiline literal or the actual TOML input can have a trailing newline, but **not both**.

```toml
# {'foo': {'bar': "[']"}}
[foo]
bar = '''[']'''

# {'foo': {}}
[foo]
bar = '''
[']
'''

# {'foo': {'bar': "[']"}} UNLESS TOML input ends in a newline
[foo]
bar = '''
[']'''
```

I just thought this behavior was incredibly strange. The workaround of course is to strip newlines from all input before it's parsed, and to ensure any multiline literals do not have trailing newlines.
