### ISSUE TITLE
dict not dumped correctly

### ISSUE THREAD

**Issue by retorquere** [uiri/toml#247]
when I run this:

```
import toml
data = {'citation-items': [[{'id': 'ITEM-1'}, {'id': 'ITEM-2'}]] }
print(toml.dumps(data))

```

I get

```
citation-items = [ [ [ "id",], [ "id",],],]
```

**Comment by n-rodriguez** [comment]
Worse:
```python
import toml
data =  {'global_tags': {}, 'outputs': {'discard': {}}, 'inputs': {'diskio': {}, 'mem': {}, 'swap': {}, 'kernel': {}, 'processes': {}, 'cpu': {'totalcpu': True, 'collect_cpu_time': False, 'report_active': False, 'percpu': True}, 'system': {}, 'disk': {'ignore_fs': ['tmpfs', 'devtmpfs', 'devfs', 'iso9660', 'overlay', 'aufs', 'squashfs']}}, 'agent': {'interval': '10s', 'metric_buffer_limit': 10000, 'flush_interval': '10s', 'collection_jitter': '0s', 'round_interval': True, 'flush_jitter': '0s', 'metric_batch_size': 1000, 'precision': '', 'hostname': '', 'omit_hostname': False}}
print(toml.dumps(data))
```

```toml
       --------TOML--------
       [agent]
       interval = "10s"
       metric_buffer_limit = 10000
       flush_interval = "10s"
       collection_jitter = "0s"
       round_interval = true
       flush_jitter = "0s"
       metric_batch_size = 1000
       precision = ""
       hostname = ""
       omit_hostname = false
       [inputs.cpu]
       totalcpu = true
       collect_cpu_time = false
       report_active = false
       percpu = true
       [inputs.disk]
       ignore_fs = [ "tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs",]
```

```yaml
       --------YAML--------
       agent: {collection_jitter: 0s, flush_interval: 10s, flush_jitter: 0s, hostname: '',
         interval: 10s, metric_batch_size: 1000, metric_buffer_limit: 10000, omit_hostname: false,
         precision: '', round_interval: true}
       global_tags: {}
       inputs:
         cpu: {collect_cpu_time: false, percpu: true, report_active: false, totalcpu: true}
         disk:
           ignore_fs: [tmpfs, devtmpfs, devfs, iso9660, overlay, aufs, squashfs]
         diskio: {}
         kernel: {}
         mem: {}
         processes: {}
         swap: {}
         system: {}
       outputs:
         discard: {}
```

**Comment by n-rodriguez** [comment]
The generated toml should like this :

```toml
########################################################################
# File managed by Salt at <salt://telegraf/files/default/telegraf.tmpl.jinja>.
# Your changes will be overwritten.
########################################################################


[outputs]

[outputs.discard]

[inputs]

[inputs.system]

[inputs.swap]

[inputs.processes]

[inputs.mem]

[inputs.kernel]

[inputs.diskio]

[inputs.disk]
ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[inputs.cpu]
collect_cpu_time = false
percpu = true
report_active = false
totalcpu = true

[global_tags]

[agent]
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
hostname = ""
interval = "10s"
metric_batch_size = 1000
metric_buffer_limit = 10000
omit_hostname = false
precision = ""
round_interval = true
```

**Comment by uiri** [comment]
Thank you for reporting this issue!

I can reproduce the bug but I am puzzled at what the expected output would be. I am not sure that an array of an array of tables is valid TOML unless they are expressed with inline tables.

**Comment by retorquere** [comment]
Good point... I may have been thinking of TOML as a more-readable JSON/YAML replacement, but that's not the use-case for TOML of course. Still, if data can't be toml-dumped, perhaps it would be useful to raise an exception?

**Comment by n-rodriguez** [comment]
> Thank you for reporting this issue!
> 
> I can reproduce the bug but I am puzzled at what the expected output would be. I am not sure that an array of an array of tables is valid TOML unless they are expressed with inline tables.

Actually it should generate this :

```toml
########################################################################
# File managed by Salt at <salt://telegraf/files/default/telegraf.tmpl.jinja>.
# Your changes will be overwritten.
########################################################################


[[outputs]]

[[outputs.discard]]

[[inputs]]

[[inputs.system]]

[[inputs.swap]]

[[inputs.processes]]

[[inputs.mem]]

[[inputs.kernel]]

[[inputs.diskio]]

[[inputs.disk]]
ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]

[[inputs.cpu]]
collect_cpu_time = false
percpu = true
report_active = false
totalcpu = true

[[global_tags]]

[[agent]]
collection_jitter = "0s"
flush_interval = "10s"
flush_jitter = "0s"
hostname = ""
interval = "10s"
metric_batch_size = 1000
metric_buffer_limit = 10000
omit_hostname = false
precision = ""
round_interval = true
```
