### ISSUE TITLE
Object in nested array has no values

### ISSUE THREAD

**Issue by jacopofar** [uiri/toml#281]
Hello and thanks for the library!

I'm trying to dump an object containing nested arrays of dictionaries, and the output TOML does not contain the values:

```python
import toml

extractors = [
    dict(
        name="Is something",
        patterns=[
            [{"LOWER": "è"}, {"TEXT": {"REGEX": "un"}}, {"POS": "NOUN"}],
        ],
        more_patterns=[
            {"LOWER": "è"}, {"TEXT": {"REGEX": "un"}}, {"POS": "NOUN"},
        ],
        template={'category': 2}),
]
obj = dict(extractors=extractors)

print(toml.dumps(obj))
```
the output is:

```TOML

[[extractors]]
name = "Is something"
patterns = [ [ [ "LOWER",], [ "TEXT",], [ "POS",],],]
[[extractors.more_patterns]]
LOWER = "è"

[[extractors.more_patterns]]

[extractors.more_patterns.TEXT]
REGEX = "un"
[[extractors.more_patterns]]
POS = "NOUN"


[extractors.template]
category = 2
```

the `patterns` list was transformed into an array of keys but the values are lost.

Is this kind of structure supported? If not I can try and make a PR to raise an error in this scenario.
