### ISSUE TITLE
numpy array written as strings

### ISSUE THREAD

**Issue by nschloe** [uiri/toml#306]
numpy arrays with float values are written as strings. When converted to a `list` of floats, it's all going well.

MWE:
```python
import toml
import numpy


numpy.random.seed(0)
x = numpy.random.rand(3)
a = {"a": x}
print(toml.dumps(a))

b = {"b": x.tolist()}
print(toml.dumps(b))
```
```toml
a = [ "0.5488135039273248", "0.7151893663724195", "0.6027633760716439",]

b = [ 0.5488135039273248, 0.7151893663724195, 0.6027633760716439,]

```
