### ISSUE TITLE
Invalid parsing of raw string (regex) with toml

### ISSUE THREAD

**Issue by laurent-laporte-pro** [uiri/toml#363]
I am using [`toml`][1] v0.10.2 to parse the following `toml` file:

```toml
[section]
'foo' = [
    { search = '__date__ \s+ = \s+ "[^"]+"' }
]
```

The result is:

```
>>> toml.loads(text)
{'section': {'foo': []}}
```

I think it is a bug.

_note 1_: I use simple quotes to insert raw string.

_note 2_: I have no issue with [`pytoml`][2]

  [1]: https://pypi.org/project/toml/0.10.2/
  [2]: https://pypi.org/project/pytoml/
