### ISSUE TITLE
Invalid handling of escaped backslashes "\\"

### ISSUE THREAD

**Issue by DemonInTheCloset** [uiri/toml#385]
I am parsing some LaTeX text into a TOML file and I get an error decoding it:

toml.dump() fails to properly handle `{"a": "\\biggr"}`, I expected it to generate:

```toml
a="\\biggr"
```

But it instead generates:

```toml
a="\biggr"
```

Which is an invalid TOML file

edit: Somehow using that small example it isn't reproducible so here is the full code:

```python
d={
    'Problem262': {
        'title': 'Mountain Range',
        'description': "The following equation represents the continuous topography of a\nmountainous region, giving the elevation h at any point (x,y):\n\n$h = \\biggr( 5000 - \\dfrac{x^2 + y^2 + xy }{200} + \\dfrac{25(x + y) }{2} \\biggr) ⋅ e^{- \\biggr\\rvert \\dfrac{x^2 + y^2 }{1000000} - \\dfrac{3(x + y) }{2000} + \\dfrac{7}{10} \\biggr\\rvert }$\n\nA mosquito intends to fly from A(200,200) to B(1400,1400), without leaving\nthe area given by 0\xa0≤\xa0x,\xa0y\xa0≤\xa01600.\n\nBecause of the intervening mountains, it first rises straight up to a\npoint A', having elevation f. Then, while remaining at the same elevation\nf, it flies around any obstacles until it arrives at a point B' directly\nabove B.\n\nFirst, determine f[min] which is the minimum constant elevation allowing\nsuch a trip from A to B, while remaining in the specified area.\nThen, find the length of the shortest path between A' and B', while flying\nat that constant elevation f[min].\n\nGive that length as your answer, rounded to three decimal places.\n\nNote: For convenience, the elevation function shown above is repeated\nbelow, in a form suitable for most programming languages:\n\n```php\nh=( 5000-0.005*(x*x+y*y+x*y)+12.5*(x+y) ) * exp( -abs(0.000001*(x*x+y*y)-0.0015*(x+y)+0.7) )\n```\n",
        'answer_hash': 'a5921e175a44d31e7f82f7f9a61a36af'
    }
}
```

The produced TOML file is this:

```toml
[Problem262]
title = "Mountain Range"
description = "The following equation represents the continuous topography of a\nmountainous region, giving the elevation h at any point (x,y):\n\n$h = \biggr( 5000 - \dfrac{x^2 + y^2 + xy }{200} + \dfrac{25(x + y) }{2} \biggr) ⋅ e^{- \biggr\rvert \dfrac{x^2 + y^2 }{1000000} - \dfrac{3(x + y) }{2000} + \dfrac{7}{10} \biggr\rvert }$\n\nA mosquito intends to fly from A(200,200) to B(1400,1400), without leaving\nthe area given by 0xa0≤xa0x,xa0yxa0≤xa01600.\n\nBecause of the intervening mountains, it first rises straight up to a\npoint A', having elevation f. Then, while remaining at the same elevation\nf, it flies around any obstacles until it arrives at a point B' directly\nabove B.\n\nFirst, determine f[min] which is the minimum constant elevation allowing\nsuch a trip from A to B, while remaining in the specified area.\nThen, find the length of the shortest path between A' and B', while flying\nat that constant elevation f[min].\n\nGive that length as your answer, rounded to three decimal places.\n\nNote: For convenience, the elevation function shown above is repeated\nbelow, in a form suitable for most programming languages:\n\n```php\nh=( 5000-0.005*(x*x+y*y+x*y)+12.5*(x+y) ) * exp( -abs(0.000001*(x*x+y*y)-0.0015*(x+y)+0.7) )\n```\n"
answer_hash = "a5921e175a44d31e7f82f7f9a61a36af"
```

And the `\biggr` `\` is not escaped
