### ISSUE TITLE
bug: unexpected list of inline table

### ISSUE THREAD

**Issue by yihengli** [uiri/toml#386]
## Case 1

```toml
list_1 = [{name=1}]
list_2 = [{name=2}]
```
by using `toml.loads(...)`, the result looks reasonable 
```
{'list_1' = [{'name': 1}], 'list_2': [{'name': 2}]}
```

## Case 2

However, if I did a typo with not paird brackets

```toml
list_1 = [{name=1}]]
list_2 = [{name=2}]
```
I am expecting this would fail as `list_1` is defined with a mismatched bracket, however, it got passed and get something I am not expecting
```
{'list_1': [{'name': 1, {'name': 2}}]}
```

This doesn't look like a standard toml rule.

> using toml 0.10.2 and python 3.7
