### ISSUE TITLE
Default TomlEncoder does not escape backslashes correctly

### ISSUE THREAD

**Issue by Poofjunior** [uiri/toml#415]
This is mainly an issue storing windows file paths. 

In a nutshell, a config containing this data:
````toml
# config.toml
[specs]
my_path = "C:\\Program Files\\Euresys\\Memento\\bin\\x86_64\\memento.exe" 
````
can be loaded with:
````python
cfg = toml.load("config.toml")
````
and then saved with:
````python
with open("new_config.toml", 'w') as f:
    f.write(toml.dumps(cfg))
````
But the result will remove the first two double backslashes for some characters that can be incorrectly parsed as valid.
````toml
# new_config.toml
[specs]
my_path = "C:\Program Files\Euresys\Memento\bin\x86_64\\memento.exe"  
````

It looks like the double-backslash is not recognized when the next character forms a valid unicode shorthand?
