### ISSUE TITLE
list object of compound type could not be parsed

### ISSUE THREAD

**Issue by EstherOnly** [uiri/toml#416]
a list object of compound type could not be parsed, not all element in list is dict object, list like
```
routes:
- filters:
  - "StringPrefix=1"
  - name: "RequestRateLimiter"
    args:
      redis-rate-limiter.replenishRate: 1000
      redis-rate-limiter.burstCapacity: 1000
      key-resolver: "#{@hostAddrKeyResolver}"
      statusCode: "METHOD_NOT_ALLOWED"
  - name: "Hystrix"
    args:
      name: "failback"
      fallbackUri: "forward:/failback"
```
element maybe str, int, datetime and so on, they should be processed here in encoder.py:
```
            if not isinstance(o[section], dict):
                arrayoftables = False
                if isinstance(o[section], list):
                    for a in o[section]:
                        if isinstance(a, dict):
                            arrayoftables = True
                if arrayoftables:
                    for a in o[section]:
                        arraytabstr = "\n"
                        arraystr += "[[" + sup + qsection + "]]\n"
                        s, d = self.dump_sections(a, sup + qsection)
```
