### ISSUE TITLE
Strings with apostrophes in within inline tables lead to empty arrays

### ISSUE THREAD

**Issue by Artemis21** [uiri/toml#436]
The following TOML:
```toml
foo = [ { x = "'" } ]
```
Gets parsed as:
```py
{'foo': []}
```

I cannot seem to reduce this example any further - the following all parse as I expect:
```toml
foo = [ "'" ]
bar = { x = "'" }

[[baz]]
x = "'"
```
