### ISSUE TITLE
[BUG] empty dict in array list will not be parsed

### ISSUE THREAD

**Issue by yihengli** [uiri/toml#440]
```python
a1 = {"a": [{"name": "bob", "kwargs": {}}]}
print(toml.dumps(a1))
```
What I got
```toml
[[a]]
name = "bob"
```
I am expecting to have
```toml
[[a]]
name = "bob"
[[a.kwargs]]
```

Latest toml and python=3.12

Not sure if this is the intended behavior
