### ISSUE TITLE
Comments support

### ISSUE THREAD

**Issue by singleton11** [uiri/toml#77]

**Comment by uiri** [comment]
Patches (Pull Requests) welcome!

I recommend saving it in some key value pairs which your code then ignores. For example:

```toml
[comments]
logging = "The logs are rotated every 2 weeks"
```

**Comment by samvasko** [comment]
or just append the changes

**Comment by ryanhiebert** [comment]
In order to implement this, we'll have to live with some ambiguity, or move to using ordered dicts everywhere. Consider this TOML file.

```toml
# This is my TOML file

[mytable]
# My table is great

# Make it greater
greater = true

greatest = true  # Make it the greatest
```

There are, sort of, two types of comments. Inline comments that appear in the same line as a line of code, and full-line comments that simply appear _near_ their code.

Because the tables are unordered, and the order may change when dumping the tables, the "best" way to preserve the comments is to relate them to a line of configuration. Inline comments are simple to do this way: just attach them to whatever was on the line with them. Whole line or multi-line comments are ambiguous, though, as they may better attach to the parent scope, or to the following configuration. Without preserving even more of the file, especially the ordering, there's not a great way to deal with this ambiguity.

We can make a choice about which is the Right Way for whole-line comments to be considered, but I'm not sure which way it is. I think I'd be inclined toward it being associated with the following item if it exists, otherwise with the parent scope.This association is guaranteed to be wrong some of the time, though, without a good solution. The only real fix for that is to make it not matter whether we get it right or not, by making sure that the keys end up staying where they need to.
